neuralmagic/yolov5

models/export.py
utils/sparse.py

* fix issue where `Path` object gets passed to `check_download_sparsezoo_weights` which raised a type error
* propagate updated file path info after sparsezoo download

relax strict type check in sparsezoo load function

---

export.py
train.py

This PR adds the option to skip over arg parsing when args are provided directly. This is added to avoid yolov5 from reading in autosparse CLI args.

Add option to skip arg parsing

---

val.py
val_onnx.py

This PR adds the missing `--data-path` args to `val.py` and `val_onnx.py`

Add missing data path args

---

export.py
utils/sparse.py

adds a quick check if an exported onnx graph requires uint8 inputs and adds a pathway to convert inputs back to uint8
**test plan**
manual via research team

pathway to save sample inputs as uint8 for onnx graphs with uint8 inputs

---

utils/neuralmagic/sparse_train_manager.py

In the case of a small user defined batch size and QAT, the grad accum steps can come out to 0. This PR patches that issue

Fix for much larger autobatch

---

utils/neuralmagic/utils.py

Bug Description: ONNX file incorrectly saved as `model.pt` instead of `model.onnx`, where 
Reproduction Steps:
1) Download the model
```bash
~ sparsezoo.download \
"zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/pruned85_quant-none" \
--save-dir yolov5_model
```
2) Export the model
The checkpoint will be downloaded to `yolov5_model/training`
export command:
```bash
sparseml.yolov5.export_onnx --weights yolov5_model/training/model.pt
```
3) Notice the filenames, the ONNX file is saved as `model.pt`:
`yolov5_model/training/DeepSparse_Deployment/model.pt`
This PR fixes the bug, 
Test:
After running the command in Step 2 again , a `model.onnx` file was produced, verfied manually

Fix: suffix of saved onnx

---

train.py

Scale gradient clipping threshold with effective batch size. This scaling is the same used for the loss (and thus gradients) and avoids gradient clipping being affected by batch size.
The threshold is set to be the same as the original code (10.0) if effective batch size is 64.

Scale gradient clipping

---

models/common.py
utils/neuralmagic/quantization.py
val.py

Fix to the bug: https://app.asana.com/0/1201735099598270/1203940813196775/f
Note: Is the difference in mAP for some models depending on the inference engine within the correct boundaries? I am a bit doubtful here.
The `pruned and quantized` model tested: zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/pruned85_quant-none
The `pruned` model tested: zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/pruned35-none-vnni
Any other models used were the default yolov5n models (.pt or .onnx)
```bash
mAP50 -> 0.711
Results saved to /home/ubuntu/damian/yolov5/yolov5_runs/val/exp68
```
```bash
mAP50 -> 0.711
DeepSparse, Copyright 2021-present / Neuralmagic, Inc. version: 1.3.2 COMMUNITY | (7d31c4bf) (release) (optimized) (system=avx2, binary=avx2)
...
Results saved to …
```

[Fix] Running `val.py` with `--deepsparse` flag

---

val.py

Fix for: https://app.asana.com/0/1201735099598270/1203967510531024
The function responsible for stdout:`val: ...` is `print_args`.  This PR moves this function from `parse_opt` method to `main(...)`
Before, the printing of args happened in the `parse_opt` function. Let's examine what was happening when we called:
`sparseml.yolov5.validation` with kwargs or without kwargs.  Let's bring up the responsible code from `sparseml`:
```python
def val(**kwargs):
"""
Hook to call into val.py in YOLOv5 fork
"""
if kwargs:
val_run(**kwargs)
else:
opt = parse_val_args()
val_run(**vars(opt))
```
Command `sparseml.yolov5.validation --something 10`. Not the happy path, but it jumps directly to the `val_run` function, so in theory, it should run `print_args` just once (inside `val_run(...)`)
Command: …

[Fix] Two confusing "val:" prints when sparseml.yolov5.validation has args specified

---

val.py

Cherry pick for: https://github.com/neuralmagic/yolov5/pull/177

[Cherry pick][Fix] Two confusing "val:" prints when sparseml.yolov5.validation has args specified

---

utils/neuralmagic/utils.py

Before: `--weights` parameter, which specified a model without the baked-in `hyps` could not be used together with `--export-samples` parameter. The missing `hyps` were silently breaking the dataset for generating samples.
Now: when `hyps` are missing, the default hyps (same defaults as in training) are evoked.
```bash
sparseml.yolov5.export_onnx --dynamic --weights model.pt --export-samples 20
```
Returns:
```bash
export: data=data/coco128.yaml, data_path=, weights=/home/ubuntu/damian/yolov5/yolov5s.pt, imgsz=[640, 640], batch_size=1, device=cpu, half=False, inplace=False, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=12, verbose=False, workspace=4, nms=False, agnostic_nms=False, topk_per_class=100, topk_all=100, iou_thres=0.45, conf_thres=0.25, …
```

Handle missing `hyps` in the exported model

---

export.py
val.py

Fix for https://app.asana.com/0/1203126676641557/1203962634484913
@anmarques I assume that the sample generation failed for you, because you were exporting a non-sparsified model. This is because the sample generation pathway only activates if `sparsified==True`. 
This condition is met if `sparsified = getattr(model, "sparsified", False) or one_shot`.
I have pulled the sample generation out of the `if-` statement, so now samples are generated regardless of the boolean value of `sparsified`
Testing:
```bash
sparseml.yolov5.export_onnx  --dynamic --export-samples 20
```
```bash
export: data=data/coco128.yaml, data_path=, weights=/home/ubuntu/damian/yolov5/yolov5s.pt, imgsz=[640, 640], batch_size=1, device=cpu, half=False, inplace=False, keras=False, optimize=False, int8=False, …
```

[Fix] Generation of input/output samples for non-sparsified models 

---

models/common.py

Cherry Pick for https://github.com/neuralmagic/yolov5/pull/190/

[Cherry Pick][Fix] Prevent the model with the flag `--deepsparse` to go through the `attempt_download()` route

---

utils/neuralmagic/utils.py

adds a pass to set the onnx graph input shape to the sample data shape even for dyanmic exports.
this is because dynamic shape export is required to change image size, however deepsparse engine requires a static input shape and static input shapes provide good information for model analysis and shape inference
depends on https://github.com/neuralmagic/sparseml/pull/1471
**test_plan**
new dynamic export: 
```bash
sparseml.yolov5.export_onnx \
--weights zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/pruned65_quant-none \
--dynamic
```
verified weights are hardcoded:
```python
>>> model.graph.input
[name: "images"
type {
tensor_type {
elem_type: 1
shape {
dim {
dim_value: 1
}
dim {
dim_value: 3
}
dim {
dim_value: 640
}
dim {
dim_value: 640
}
}
}
}
]
```
dynamic inference:
```
from …
```

add hardcoded onnx graph input shape even for dyanmic exports

---

utils/neuralmagic/utils.py

required for dynamic batch compatibility with ORT (doesn't affect deepsparse)
requires: https://github.com/neuralmagic/sparseml/pull/1478
**test_plan:**
re-ran all tests from #193 + tested the resulting model against `deepsparse.benchmark` and `sparsezoo.analyze`

[ONNX export] keep BATCH dimension dynamic

---

export.py

following this patch, models trained without a recipe will also go through sparseml onnx export. This will ensure that their input dimensions are compatible with deepsparse and its tooling

always use sparseml onnx export

---

setup.py
utils/neuralmagic/version.py

moving forward build versions will by synced with the latest NM release (patch version is async) with the fourth slot either the nightly date for nightly or the base yolov5 version for release
example nightly: `1.5.0.20230331`
example release: `1.5.0.60201`

update build versions for NM fork pypi push

---

train.py

#200 included a side change to remove the now unused `image_size` arg from the function signature but did not update the call site.
this PR fixes that.
**test_plan:**
Reproduced reported error with a sample quantization recipe and verified this PR resolves it

[fix] remove image_size from call to rescale_gradient_accumulation

---

train.py

#200 included a side change to remove the now unused `image_size` arg from the function signature but did not update the call site.
this PR fixes that.
**test_plan:**
Reproduced reported error with a sample quantization recipe and verified this PR resolves it

[fix] remove image_size from call to rescale_gradient_accumulation (#202)

---

train.py

#200 included a side change to remove the now unused `image_size` arg from the function signature but did not update the call site.
this PR fixes that.
**test_plan:**
Reproduced reported error with a sample quantization recipe and verified this PR resolves it

[fix] remove image_size from call to rescale_gradient_accumulation (#202(

---

utils/neuralmagic/utils.py

workflows didn't trigger on last commit to release/1.4 for unknown reason.
fixing typo I found to attempt to re-trigger

no-op to trigger release/1.4 workflows

---

utils/neuralmagic/utils.py

Restores the logic to change the onnx graph such that it expects UNIT8 inputs for quantized models. This logic was lost in the upstream integration.

Use INT8 input for quantized models

---

export.py
train.py

This PR fixes a bug where args are read from the CLI regardless of the skip_parse setting. When YOLOv5 is run by another program (such as Sparsify), we want to enable skip_parse so that the CLI args to sparsify aren't read in as CLI argument to YOLOv5

[Bug-fix] Remove non-conditional reading of kwargs

---

requirements.txt

`Pillow` 10.0.0 appears to trigger the following error, pinning to lower until resolved
```python
"AttributeError: 'FreeTypeFont' object has no attribute 'getsize'" and missing expected files
```
**test_plan:**
reproduced and verified locally

Pin Pillow version to <10.0.0

---

export.py

Logic for quantization of inputs was already in the codebase, but was being bypassed because the onnx path was not passed to the export samples function. This PR fixes that.
Testing plan: tested on yolov5-s base_quant and verified inputs are properly quantized

Enable quantization of inputs

---

utils/neuralmagic/utils.py

For this bug: https://app.asana.com/0/1204322589046915/1205070658998384/f
This will update the case to make sure the exported model is called`model.onnx`
Verified correctness through local testing

Update the yolo model to always be exported as model.onnx
